# Generated by Django 5.2.4 on 2025-07-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greentech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
