# Generated by Django 5.2.4 on 2025-07-23 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greentech', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 23, 4, 2, 33, 14304, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
