# Generated by Django 5.2.4 on 2025-07-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greentech', '0006_feedback_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone #')),
                ('area_of_interest', models.CharField(max_length=200)),
                ('availability', models.CharField(help_text='e.g. weekends, weekdays, evenings', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
