# Generated by Django 5.2.4 on 2025-07-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greentech', '0007_volunteerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Denied')], default='P', help_text='Admin can Accept or Deny', max_length=1),
        ),
    ]
