# Generated by Django 5.2.4 on 2025-07-29 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greentech', '0010_volunteerrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='greentech.greenpost'),
        ),
    ]
