# Generated by Django 5.2.4 on 2025-07-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greentech', '0011_feedback_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteerapplication',
            options={'verbose_name': 'Community Request', 'verbose_name_plural': 'Community Requests'},
        ),
    ]
