# Generated by Django 5.2.1 on 2025-07-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greentech', '0012_alter_volunteerapplication_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteerapplication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='volunteerrequest',
            options={'verbose_name': 'Community Request', 'verbose_name_plural': 'Community Requests'},
        ),
    ]
